language: node_js
node_js:
  - 16
script:
  - npm run lint
  - npm run test
  - npm run build
  - nyc --silent npm run test
after_success:
  - NODE_ENV=production npm run build
  - semantic-release
notifications:
  email: false
sudo: false
